# Generated by Django 2.1.4 on 2018-12-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0002_auto_20181227_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
